<?php
/**
 * Broodle WHMCS Tools - Hook Bridge
 *
 * This file ensures the addon module hooks are loaded reliably.
 * WHMCS auto-loads all .php files in includes/hooks/ on every request.
 * Auto-generated by Broodle WHMCS Tools — do not edit manually.
 *
 * @see modules/addons/broodle_whmcs_tools/hooks.php
 */

if (!defined("WHMCS")) {
    die("This file cannot be accessed directly.");
}

$broodleHooksFile = ROOTDIR . "/modules/addons/broodle_whmcs_tools/hooks.php";
if (file_exists($broodleHooksFile)) {
    require_once $broodleHooksFile;
}
